### ISSUE TITLE
White image file not found.

### ISSUE THREAD

**Issue by jinweiwong** [hahnec/plenopticam#25]
Hi, I keep on getting the ```White image file not present``` error message when I use the raw.lfp and tar calibration data obtained from my Lytro Illum camera. But when I use the data downloaded from the INRIA Dataset, it works completely fine. I am using plenopticam v0.8.2. I have a macOS 12.3 Monterey with M1 chip. 

Here is the [Google Drive link](https://drive.google.com/drive/folders/1D9fnmI36DAN78eOzIOCIOai5FDC3n0br?usp=sharing) for my two files.

Full error message:
```
 Loading data

 Potential data loss as directory already exists.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/lfp_reader/top_level.py", line 64, in main
    self.decode_lytro_file()
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/lfp_reader/top_level.py", line 106, in decode_lytro_file
    obj.main()
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/lfp_reader/lfp_decoder.py", line 71, in main
    self.decode_lfc()
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/lfp_reader/lfp_decoder.py", line 104, in decode_lfc
    sec_idx = self.get_idx(sections, int(self._shape[0] * self._shape[1] * self.cfg.lfpimg['bit'] / 8))[0]
KeyError: 'bit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/gui/widget_ctrl.py", line 366, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/gui/widget_ctrl.py", line 277, in load_lfp
    lfp_obj.main()
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/lfp_reader/top_level.py", line 73, in main
    raise LfpTypeError(e, cfg=self.cfg)
plenopticam.misc.errors.LfpTypeError: 'bit'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/gui/widget_ctrl.py", line 366, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/gui/widget_ctrl.py", line 261, in auto_find
    obj.main()
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/lfp_calibrator/cali_finder.py", line 105, in main
    self._search_tar_file(self._path)
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/lfp_calibrator/cali_finder.py", line 265, in _search_tar_file
    self._match_georef(json_dict)
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/lfp_calibrator/cali_finder.py", line 166, in _match_georef
    for item in json_dict[key1]:
KeyError: 'frame'

 White image file not present
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/gui/widget_ctrl.py", line 366, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/gui/widget_ctrl.py", line 252, in cal
    cal_obj.main()
  File "/opt/homebrew/lib/python3.9/site-packages/plenopticam/lfp_calibrator/top_level.py", line 58, in main
    if len(self._wht_img.shape) == 2 and 'bay' in self.cfg.lfpimg:
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by hahnec** [comment]
The json metadata provided in your Lytro calibration tar-archive is significantly different from what I have seen so far. Because of that the camera model couldn't be recognized by the tool. In particular, the serial number of your camera doesn't start with a letter, which usually indicates the Lytro model. 

I made changes with commit 730c9587e63caddf9317e47c586d102ae1645d29 to now consider your model number and managed to render your SanFran mug on my side. While I’m working towards a new release, you could pull from the [develop](https://github.com/hahnec/plenopticam/tree/develop) branch and run ```main.py``` in the plenopticam folder to render your camera's raw images in the meantime.

**Comment by jinweiwong** [comment]
Thanks so much for the speedy fix, it works perfectly now!
