### ISSUE TITLE
Issues loading OpEx dataset images

### ISSUE THREAD

**Issue by Kelvin-Chan** [hahnec/plenopticam#5]
Hello!

I've recently been getting involved in researching application using plenoptic cameras and depth estimation, and I came across this Python library! I am trying to run the [OpEx](https://ndownloader.figshare.com/files/5201452) dataset, using the calibration and image .BMP file located at the root of the dataset directory (f197Inf9pxFinalShift12.7cmf22.bmp and f197Inf9pxFinalShift12.7cm.bmp), but I am getting an error about a NoneType for `self._wht_img`.

```
(heka) kelvinchan@Quadro:~/Desktop/OpEx$ plenopticam -g

Plenopticam 0.2.0 by Christopher Hahne


 Starting ...

 Provided file /home/kelvinchan/Desktop/OpEx/f197Inf9pxFinalShift12.7cm/f197Inf9pxFinalShift12.7cm.json does not exist

 White image file not present
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/tkinter/__init__.py", line 746, in callit
    func(*args)
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/site-packages/plenopticam-0.2.0-py3.6.egg/plenopticam/gui/widget_ctrl.py", line 147, in poll
    self.cur_thread.join()
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/site-packages/plenopticam-0.2.0-py3.6.egg/plenopticam/gui/widget_ctrl.py", line 341, in join
    raise misc.errors.PlenopticamError(self.exc, cfg=self.cfg, sta=self.sta)
plenopticam.misc.errors.PlenopticamError: Traceback (most recent call last):
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/site-packages/plenopticam-0.2.0-py3.6.egg/plenopticam/gui/widget_ctrl.py", line 333, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/site-packages/plenopticam-0.2.0-py3.6.egg/plenopticam/gui/widget_ctrl.py", line 256, in cal
    cal_obj.main()
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/site-packages/plenopticam-0.2.0-py3.6.egg/plenopticam/lfp_calibrator/top_level.py", line 50, in main
    self._wht_img = rgb2gray(self._wht_img) if len(self._wht_img.shape) is 3 else self._wht_img
AttributeError: 'NoneType' object has no attribute 'shape'
```

It also complains about the missing JSON for the calibration image, but that does not exist in this dataset. If this issue is due to the missing JSON, what are the values that Plenopticam expect in the calibration JSON?

**Comment by hahnec** [comment]
Hi Kelvin, 

The missing JSON file is due the white image calibration not finishing correctly which in turn is a result of `self._wht_img` being `None`. I was able to reproduce you problem in version 0.2.0 and saw that it persisted with the version I am currently working on. So, thanks for pointing it out! I managed to fix it and will publish a new version in the upcoming days. Will let you know about a new release here to see if things have resolved on your side.

Best
Chris

**Comment by hahnec** [comment]
Please try to install a newer version with `pip3 install -i https://test.pypi.org/simple/ plenopticam==0.3.0`

Does this solve the issue on your side?

**Comment by Kelvin-Chan** [comment]
Yes, it works perfectly now, I was able to get all the expected stacks! The only thing that I encountered with this particular revision is that TK complains about a missing GIF file instead of trying to use the ICNS file in the directory, which I was able to bypass by converting the ICNS to GIF and placing it at the same location.

```
(heka) kelvinchan@Quadro:~/microlens-depth$ plenopticam -g

Plenopticam v0.3.0 

Traceback (most recent call last):
  File "/home/kelvinchan/anaconda3/envs/heka/bin/plenopticam", line 11, in <module>
    sys.exit(main())
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/site-packages/plenopticam/bin/cli_script.py", line 125, in main
    cfg = parse_options(sys.argv[1:], cfg)
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/site-packages/plenopticam/bin/cli_script.py", line 79, in parse_options
    PlenopticamApp(None).mainloop()
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/site-packages/plenopticam/gui/top_level.py", line 55, in __init__
    self.icon_handling()
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/site-packages/plenopticam/gui/top_level.py", line 77, in icon_handling
    logo = tk.PhotoImage(file=fp)
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/tkinter/__init__.py", line 3542, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/tkinter/__init__.py", line 3498, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "/home/kelvinchan/anaconda3/envs/heka/lib/python3.6/site-packages/plenopticam/gui/icns/1055104.gif": no such file or directory

```

**Comment by hahnec** [comment]
Thanks for pointing that out! I wasn't able to trigger this icon error on my system. Which OS are you using? Guessing what might have been causing this, I tried to cover the icon file issue in v0.3.1 which is also found at

pip3 install -i https://test.pypi.org/simple/ plenopticam==0.3.1

Can you pls let me know whether this worked for you?

**Comment by Kelvin-Chan** [comment]
I am on Ubuntu 18.04, running `plenopticam` within an Anaconda environment set to Python 3.6.6.
Yup, I've tried this wheel file and the icon error does not appear now!
